### ISSUE TITLE
OH!

### ISSUE THREAD

**Issue by DongGeon0908** [pennya6/DO-IT-JAVA#1]
저도 Do-IT-JAVA로 공부했는데 내용이 간단해서 쉽게 느껴질 것 같아요
자바의 꽃은 OOP입니당

java를 더 공부할거면 JPA와 OOP를 공부하는게 좋을 것 같아용!

그리고 만약 OOP랑 JPA가 어렵다면 '이것이 자바다' 이 책도 좋아요~

홧팅

**Comment by DongGeon0908** [comment]
아! 그리고 조금 더 공부하고 싶다면, 백준 온라인 저지를 시작하는 것도 좋아요

**Comment by pennya6** [comment]
감사합니다!!
​
-----Original Message-----

**Comment by pennya6** [comment]
감사합니다 ㅠㅠ  참고해서 공부해보도록 할게요!!
